# Generated by Django 4.0.5 on 2022-09-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_desc',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='title',
        ),
    ]
