# Generated by Django 4.0.5 on 2022-09-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapi', '0002_rename_task_desc_task_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='was_published',
            new_name='time_create',
        ),
        migrations.AddField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
